[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "ls -la",             # для дебага, покажет что в папке
  "cat requirements.txt", # покажет содержимое, чтобы проверить
  "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"